package ar.edu.unq.cpi.carService.vehiculo;

public enum NivelDeVehiculo {
	AGUA_SAPITO, AGUA_RADIADOR, GRADO_SUCIEDAD, 
	DESVIO_ALINEACION, 
	CANTIDAD_BOLLOS, CANTIDAD_RAJADURAS, 
	CANTIDAD_ACEITE, CANTIDAD_NAFTA, DESGASTE_FILTRO, DESGASTE_TAPA_CILINDRO,
	PRESION_DELANTERA, PRESION_TRASERA
}
