package ar.edu.unq.cpi.carService.service;

public enum TipoServicio {
	CARGA_DE_AGUA, ALINEACION, ELIMINACION_BOLLOS, ELIMINACION_RAJADURAS, PINTURA, SERVICE_TOTAL_CHAPA,  
	CARGA_ACEITE, CARGA_NAFTA, CAMBIO_BUJIA, LIMPIEZA_EXTERIOR, 
	SACAR_ACEITE, CAMBIO_FILTRO, SACAR_AGUA, LIMPIAR_TANQUE_DE_NAFTA
}
